Repository vtex-apps/store, pull requests merged in 2018-08, with the labels that each got.

#43 OrderForm Context
  CHANGELOG.md
  manifest.json
  react/OrderFormContext.js
  react/StoreContextProvider.js
  react/mutations/addToCartMutation.gql
  react/queries/orderFormQuery.gql
Labels: enhancement

#54 OrderForm Context
  CHANGELOG.md
  manifest.json
  react/StoreContextProvider.js
Labels: enhancement

#53 ProductSearchContext dataLayer fix
  CHANGELOG.md
  manifest.json
  react/ProductContextProvider.js
  react/ProductSearchContextProvider.js
  react/components/SearchQueryContainer.js
  react/constants/searchContext.js
  react/helpers/searchHelpers.js
Labels: bug

#61 Fix the update orderForm items function
  CHANGELOG.md
  react/OrderFormContext.js
  react/mutations/updateItemsMutation.gql
Labels: bug

#56 Change breadcrumbs props
  CHANGELOG.md
  react/ProductContextProvider.js
  react/ProductSearchContextProvider.js
Labels: enhancement

#70 Add update profile data mutation
  CHANGELOG.md
  manifest.json
  react/OrderFormContext.js
  react/mutations/updateOrderFormProfile.gql
Labels: enhancement

#74 Throw specific error when the product is not found on product resolver in catalog
  CHANGELOG.md
  manifest.json
  react/OrderFormContext.js
  react/ProductContextProvider.js
Labels: enhancement

#75 Add recommendations in productQuery
  CHANGELOG.md
  manifest.json
  react/queries/productQuery.gql
Labels: enhancement

#79 Add SKU data to the benefit in the `productQuery` and fix products is undefined error on SearchContext
  CHANGELOG.md
  manifest.json
  react/ProductSearchContextProvider.js
  react/queries/productQuery.gql
Labels: bug, enhancement
