Repository vtex-apps/store, pull requests merged in 2018-07, with the labels that each got.

#18 Add the SearchResult's GraphQL queries to the SearchPage
  CHANGELOG.md
  react/SearchPage.js
  react/constants/propTypes.js
  react/constants/searchSortOptions.js
  react/helpers/searchHelpers.js
  react/queries/facetsQuery.gql
  react/queries/searchQuery.gql
Labels: enhancement

#17 Bump my-orders beta version
  CHANGELOG.md
  manifest.json
Labels: beta

#29 Change reverse path evaluation to not use pages.json
  CHANGELOG.md
  react/components/SearchQueryContainer.js
  react/helpers/searchHelpers.js
Labels: bug

#32 Passing loading information to the ProductDetails component
  CHANGELOG.md
  manifest.json
  react/ProductContextProvider.js
Labels: enhancement

#41 Delete all unnecessary path manipulation to not need pages information.
  CHANGELOG.md
  manifest.json
  react/components/SearchQueryContainer.js
  react/helpers/searchHelpers.js
Labels: enhancement
