Repository vtex-apps/store, pull requests merged in 2024-10, with the labels that each got.

#585 add: possibility to add more than one custom header per account
  CHANGELOG.md
  manifest.json
  messages/ar-SA.json
  messages/ar.json
  messages/bg.json
  messages/ca.json
  messages/context.json
  messages/de.json
  messages/en.json
  messages/es.json
  messages/fr.json
  messages/id-ID.json
  messages/ko.json
  messages/nl.json
  messages/nn.json
  messages/no-NO.json
  messages/no.json
  messages/pt.json
  messages/ro.json
  messages/th.json
Labels: enhancement

#587 Fix thai translation
  CHANGELOG.md
  messages/th.json
Labels: enhancement

#588 fix: typo in context message keys
  CHANGELOG.md
  messages/context.json
Labels: bug

#589 Refactor/custom header messages
  CHANGELOG.md
  messages/ar-SA.json
  messages/ar.json
  messages/bg.json
  messages/ca.json
  messages/context.json
  messages/de.json
  messages/en.json
  messages/es.json
  messages/fr.json
  messages/id-ID.json
  messages/ko.json
  messages/nl.json
  messages/nn.json
  messages/no-NO.json
  messages/no.json
  messages/pt.json
  messages/ro.json
  messages/th.json
Labels: chore
